default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password:
  host: db

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  database: example_production
  adapter: postgresql
  host: localhost
  password:
