default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: superpowered
  password: superpowered
  host: localhost

development:
  <<: *default
  database: development

development_docker:
  <<: *default
  database: development
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: test

production:
  database: example_production
  adapter: postgresql
  host: localhost
  password:
